# Generated by Django 4.2 on 2023-04-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('objects', '0002_saleskeys_a_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleskeys',
            name='products',
            field=models.ManyToManyField(to='products.product'),
        ),
    ]
