# Generated by Django 4.2 on 2023-04-16 08:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
        ('objects', '0003_saleskeys_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SalesKeys',
            new_name='SalesObject',
        ),
    ]
